version: '3.4'

services:
  streamer:
    build:
      context: ./streamer
    image: dazn/streamer-api
    ports:
      - "5100:5100"
    environment:
      PORT: 5100
    command: npm run dev
    restart: always

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db