version: '3.4'

services:
  streamer:
    build:
      target: dependencies
    volumes:
      - ./streamer:/home/node/app
    environment:
      # DB_PROVIDER: 'MONGO_DB'
      DB_PROVIDER: 'MEMORY_DB'